// GENERATED by tools/sync-core.mjs from solar-system/index.html — do not edit here.
// The N-body physics core of the Solar System sim (AU, years, solar masses), DOM-free.
// createSolarCore() returns a fresh, independent instance.
function createSolarCore(){

  // Everything between the SS-CORE markers is DOM-free physics + detection —
  // tools/solar-system-sim-test.mjs extracts and runs it under node. Keep
  // rendering/UI out of this block; EMIT/FX below are its only outward hooks.
  // ---- Physics — units: AU, years, solar masses (so G = 4π²) ----
  const G = 4 * Math.PI * Math.PI;
  const DT = 0.0002;       // years/step (~1.75 hrs) → resolves even the Moon's 27-day orbit
  const KMS = 4.74057;     // 1 AU/yr in km/s
  let timeRate = 6, lastRate = 6;   // signed playback rate: + forward, − reverse (Verlet is reversible), 0 = paused
  // Outward hooks: EMIT(type, data) narrates events (feed + sfx), FX(kind, data)
  // triggers wall-clock effects (sparks, shake, slow-mo). The page assigns both
  // after the UI exists; the node harness stubs them.
  let EMIT = function(){}, FX = function(){};

  const SUN = { name:'Sun', color:'#ffd35a', size:0, m:1, sun:true, R:4.6505e-3 };
  // Real orbital elements (semi-major axis AU, eccentricity), masses (solar masses)
  // and physical radii R (AU) — a spacecraft that dips below R has crashed
  const planets = [
    { name:'Mercury', color:'#b9b0a3', size:2.2, m:1.6601e-7, a:0.387,  e:0.2056, R:1.631e-5 },
    { name:'Venus',   color:'#e6c87a', size:3.9, m:2.4478e-6, a:0.723,  e:0.0068, R:4.045e-5 },
    { name:'Earth',   color:'#5aa2ff', size:4.1, m:3.0035e-6, a:1.000,  e:0.0167, R:4.259e-5 },
    { name:'Mars',    color:'#d9603b', size:2.7, m:3.2263e-7, a:1.524,  e:0.0934, R:2.266e-5 },
    { name:'Jupiter', color:'#d2a679', size:7.5, m:9.5425e-4, a:5.203,  e:0.0489, R:4.673e-4 },
    { name:'Saturn',  color:'#e0cd96', size:6.6, m:2.8576e-4, a:9.537,  e:0.0565, R:3.893e-4 },
    { name:'Uranus',  color:'#a6dde6', size:5.0, m:4.3645e-5, a:19.191, e:0.0457, R:1.695e-4 },
    { name:'Neptune', color:'#5572d6', size:4.9, m:5.1490e-5, a:30.07,  e:0.0113, R:1.646e-4 },
  ];
  const EARTH = planets[2];
  const MOON  = { name:'Moon', color:'#cfd3da', size:2.0, m:3.694e-8, aM:0.00257, eM:0.0549, moon:true, R:1.161e-5 };
  const bodies = [SUN, ...planets, MOON];
  for (const b of bodies) b.m0 = b.m;          // birth masses: reset() puts an edited mass back (a 10× Jupiter used to survive R)
  const MOON_EXAG = 10;    // Moon's true 0.00257 AU is sub-pixel — orbit drawn ×this so it's visible (HUD shows the factor)
  // Earth "planet view" orbiters at their TRUE orbit radii (km), shown through a log-of-altitude scale (so the thin LEO
  // shell spreads and the Earth→Moon gap compresses, with Earth drawn big). Real altitudes/ordering; SPEEDS are still
  // illustrative — a ~92-min ISS orbit can't be resolved at a 1.75-hr step — tuned so inner = faster.
  const ER_KM = 6371, AU_KM = 1.495979e8;   // Earth radius, 1 AU
  const EARTH_SPIN = 0.05;   // yr per rotation (illustrative). The Geo sat shares this exactly → it stays over one spot.
  const EV_SATS = [
    { name:'ISS',     rkm:6779,  period:0.015, phase:0.6, color:'#eef2f8', size:2.2 },
    { name:'Hubble',  rkm:6911,  period:0.020, phase:2.3, color:'#aebccf', size:2.0 },
    { name:'GPS',     rkm:26600, period:0.040, phase:4.1, color:'#bfe3b8', size:2.0 },
    { name:'Geo sat', rkm:42164, period:EARTH_SPIN, phase:0, color:'#e8d3a0', size:2.2, geo:true },
  ];
  let t = 0, E0 = 0, dashFlow = 0;
  let evClock = 0, lastTs = 0;   // planet-view animation clock — steady wall-clock pace, independent of sim playback speed
  const EV_SPEED = 0.003;        // "years" of planet-clock per real second → Earth rotates ≈ every 16 s
  let comets = [], flashes = [], cometSeq = 0;
  let probes = [];   // spacecraft: massless test particles on transfer orbits (feel gravity, never perturb)
  let storm = [];   // lightweight bulk test-particles (the "Storm" button) — NOT in the table, never perturb
  let belt = [];    // ambient asteroid belt (Mars↔Jupiter) — same test-particle physics as storm, always on
  let detAcc = 0;   // sim-years since the last detector pass (events check on sim cadence, not frame rate)
  let warping = 1;  // last warp factor (HUD shows ▸▸ while an approach is being fast-forwarded)
  let launches = [], launchDir = 1;   // planet-view satellite launches: animated ascent → circular orbit insertion
  let baryX = 0, baryY = 0;   // mass-weighted centre of the whole system (cached per frame); the view centres here
  function curBary(){
    let mx = 0, my = 0, M = 0;
    for (const b of bodies){ if (b.deleted) continue; mx += b.m*b.x; my += b.m*b.y; M += b.m; }
    for (const c of comets){ if (c.m > 1e-9){ mx += c.m*c.x; my += c.m*c.y; M += c.m; } }
    return [mx/M, my/M];
  }

  // ---- runtime-added planets (the "add a planet" tool) ----
  // An added body is a full member of the N-body system: it pulls, gets pulled,
  // leaves a trail, can be ejected or swallowed. reset() discards them.
  function addPlanet(p){
    p.added = true; p.trail = p.trail || []; p.deleted = false; p._ub = 0; p._glow = 0; p._ejected = false; p._reb = 0;
    planets.push(p); bodies.push(p);
    E0 = energy();
    return p;
  }
  function reset(){
    // discarded added planets are flagged deleted too, so anything still holding one
    // (the camera follow, a drag in progress) lets go the same way it does for a swallowed body
    for (let i = planets.length-1; i >= 0; i--) if (planets[i].added){ planets[i].deleted = true; planets.splice(i, 1); }
    for (let i = bodies.length-1;  i >= 0; i--) if (bodies[i].added)  bodies.splice(i, 1);
    SUN.x = 0; SUN.y = 0; SUN.vx = 0; SUN.vy = 0;
    for (const p of planets){
      p.x = p.a * (1 - p.e); p.y = 0;
      p.vx = 0;
      // vis-viva perihelion speed about the Sun, with the proper two-body μ = G(M_sun + m_planet)
      p.vy = 2*Math.PI * Math.sqrt((1 + p.m) * (1 + p.e) / (p.a * (1 - p.e)));
    }
    const vM = 2*Math.PI * Math.sqrt((EARTH.m + MOON.m) * (1 + MOON.eM) / (MOON.aM * (1 - MOON.eM)));
    MOON.x = EARTH.x + MOON.aM * (1 - MOON.eM); MOON.y = EARTH.y;
    MOON.vx = EARTH.vx; MOON.vy = EARTH.vy + vM;
    // shift to the barycentric frame: zeros total momentum AND preserves every body's velocity
    // relative to the Sun (so the orbits keep their stated elements)
    let px = 0, py = 0, M = 0;
    for (const b of bodies){ px += b.m*b.vx; py += b.m*b.vy; M += b.m; }
    const vcx = px/M, vcy = py/M;
    for (const b of bodies){ b.vx -= vcx; b.vy -= vcy; }
    for (const b of bodies){ b.trail = []; b.deleted = false; b._ub = 0; b._glow = 0; b._ejected = false; b._reb = 0; if (b.m0 !== undefined) b.m = b.m0; }
    MOON.rel = []; MOON._torn = false; MOON._ubE = 0;
    const wasRun = t > 0.05;                       // suppress the toast on initial page load
    comets = []; flashes = []; cometSeq = 0; storm = []; launches = []; probes = []; detAcc = 0;
    seedBelt();
    if (typeof deselect === 'function') deselect();
    t = 0; E0 = energy();
    if (wasRun) EMIT('reset', {});
  }

  // ---- Calendar placement: mean orbital elements → where each planet is on a date ----
  // Mean longitude L and longitude of perihelion ϖ at J2000 with per-century rates
  // (Standish's "Keplerian elements for approximate positions", valid 1800–2050).
  // The sim's own a/e stay authoritative so every orbit keeps its stated shape; the
  // orbits are flattened into one plane (dropping Mercury's 7° tilt shifts its
  // projected longitude by well under a degree), so positions land within about a
  // degree of the real sky for the inner planets and better than that further out.
  const J2000 = { Mercury: [252.25032350, 149472.67411175,  77.45779628,  0.16047689],
                  Venus:   [181.97909950,  58517.81538729, 131.60246718,  0.00268329],
                  Earth:   [100.46457166,  35999.37244981, 102.93768193,  0.32327364],
                  Mars:    [ -4.55343205,  19140.30268499, -23.94362959,  0.44441088],
                  Jupiter: [ 34.39644051,   3034.74612775,  14.72847983,  0.21252668],
                  Saturn:  [ 49.95424423,   1222.49362201,  92.59887831, -0.41897216],
                  Uranus:  [313.23810451,    428.48202785, 170.95427630,  0.40805281],
                  Neptune: [-55.12002969,    218.45945325,  44.96476227, -0.32241464] };
  const JD_J2000 = 2451545.0;
  // Julian Day at 0h UTC of a Gregorian calendar date.
  function julianDay(y, m, d){
    const a = Math.floor((14-m)/12), yy = y + 4800 - a, mm = m + 12*a - 3;
    return d + Math.floor((153*mm+2)/5) + 365*yy + Math.floor(yy/4) - Math.floor(yy/100) + Math.floor(yy/400) - 32045 - 0.5;
  }
  // Heliocentric state of a planet on Julian Day jd: {x, y, vx, vy} in AU and AU/yr, plus
  // its true longitude lon (rad) and perihelion longitude w (rad). Null for added bodies.
  function elementsAt(p, jd){
    const el = J2000[p.name]; if (!el) return null;
    const T = (jd - JD_J2000)/36525, rad = Math.PI/180;
    const L = (el[0] + el[1]*T)*rad, w = (el[2] + el[3]*T)*rad, e = p.e, a = p.a;
    let M = L - w; M = ((M % (2*Math.PI)) + 3*Math.PI) % (2*Math.PI) - Math.PI;
    let E = M + e*Math.sin(M);                                   // Kepler's equation by Newton's method
    for (let i = 0; i < 20; i++){ const f = E - e*Math.sin(E) - M; E -= f/(1 - e*Math.cos(E)); if (Math.abs(f) < 1e-13) break; }
    const mu = G*(SUN.m + p.m), se = Math.sqrt(1-e*e), r = a*(1 - e*Math.cos(E));
    const xp = a*(Math.cos(E) - e), yp = a*se*Math.sin(E), k = Math.sqrt(mu*a)/r, vxp = -k*Math.sin(E), vyp = k*se*Math.cos(E);
    const cw = Math.cos(w), sw = Math.sin(w);
    const x = xp*cw - yp*sw, y = xp*sw + yp*cw;
    return { x, y, vx: vxp*cw - vyp*sw, vy: vxp*sw + vyp*cw, lon: Math.atan2(y, x), w, r };
  }
  // Rebuild the solar system as it stands on Julian Day jd (a fresh reset, then every
  // planet moved to its dated position; the Moon rides along with Earth).
  function arrangeForDate(jd){
    reset();
    for (const p of planets){
      const s = elementsAt(p, jd); if (!s) continue;
      p.x = SUN.x + s.x; p.y = SUN.y + s.y; p.vx = SUN.vx + s.vx; p.vy = SUN.vy + s.vy;
    }
    const vM = 2*Math.PI * Math.sqrt((EARTH.m + MOON.m) * (1 + MOON.eM) / (MOON.aM * (1 - MOON.eM)));
    MOON.x = EARTH.x + MOON.aM * (1 - MOON.eM); MOON.y = EARTH.y;
    MOON.vx = EARTH.vx; MOON.vy = EARTH.vy + vM;
    MOON.rel = []; MOON._torn = false; MOON._ubE = 0;
    let px = 0, py = 0, M = 0;                                   // barycentric frame again: momentum zero, relative velocities intact
    for (const b of bodies){ if (b.deleted) continue; px += b.m*b.vx; py += b.m*b.vy; M += b.m; }
    const vcx = px/M, vcy = py/M;
    for (const b of bodies){ b.vx -= vcx; b.vy -= vcy; b.trail = []; }
    E0 = energy();
    return jd;
  }

  // ---- Ambient asteroid belt — ~240 test particles on mildly eccentric prograde orbits ----
  function seedBelt(){
    belt = [];
    for (let i = 0; i < 240; i++){
      const a = 2.1 + Math.random()*1.2, ang = Math.random()*2*Math.PI;
      const r = a * (1 - Math.random()*0.1);       // mild radial scatter (≈ e up to 0.1)
      const v = 2*Math.PI * Math.sqrt(SUN.m / r) * (1 + (Math.random()-0.5)*0.05);
      belt.push({ x: SUN.x + r*Math.cos(ang), y: SUN.y + r*Math.sin(ang),
                  vx: SUN.vx - v*Math.sin(ang),  vy: SUN.vy + v*Math.cos(ang) });
    }
  }

  // ---- N-body ----
  function accels(){
    const n = bodies.length, ax = new Array(n).fill(0), ay = new Array(n).fill(0);
    for (let i=0;i<n;i++){ if (bodies[i].deleted) continue;
    for (let j=i+1;j<n;j++){
      if (bodies[j].deleted) continue;
      const dx = bodies[j].x-bodies[i].x, dy = bodies[j].y-bodies[i].y;
      const r2 = dx*dx+dy*dy, inv = G/(r2*Math.sqrt(r2));
      ax[i] += inv*bodies[j].m*dx; ay[i] += inv*bodies[j].m*dy;
      ax[j] -= inv*bodies[i].m*dx; ay[j] -= inv*bodies[i].m*dy;
    }}
    // massive comets / interlopers pull on the planets too (test-particle comets are
    // skipped, and so are dead ones — they linger in the array until end-of-frame)
    for (const c of comets){
      if (c.dead || !(c.m > 1e-9)) continue;
      for (let i=0;i<n;i++){
        if (bodies[i].deleted) continue;
        const dx = c.x-bodies[i].x, dy = c.y-bodies[i].y, r2 = dx*dx+dy*dy+1e-4;  // same softening as cometAccel (Newton's 3rd law)
        const inv = G*c.m/(r2*Math.sqrt(r2));
        ax[i] += inv*dx; ay[i] += inv*dy;
      }
    }
    return [ax, ay];
  }
  function stepAll(dt){
    const [ax, ay] = accels();
    for (let i=0;i<bodies.length;i++){
      const b = bodies[i]; if (b.deleted) continue;
      b._px = b.x; b._py = b.y;                      // pre-step position: spacecraft sub-steps interpolate the planets across the step
      b.x += b.vx*dt + 0.5*ax[i]*dt*dt; b.y += b.vy*dt + 0.5*ay[i]*dt*dt;
      b._ax = ax[i]; b._ay = ay[i];
    }
    const [bx, by] = accels();
    for (let i=0;i<bodies.length;i++){
      const b = bodies[i]; if (b.deleted) continue;
      b.vx += 0.5*(b._ax + bx[i])*dt; b.vy += 0.5*(b._ay + by[i])*dt;
    }
  }
  function energy(){
    const all = bodies.filter(b => !b.deleted).concat(comets.filter(c => !c.dead && c.m > 1e-9));   // include live massive interlopers
    let ke = 0, pe = 0;
    for (const b of all) ke += 0.5*b.m*(b.vx*b.vx + b.vy*b.vy);
    for (let i=0;i<all.length;i++) for (let j=i+1;j<all.length;j++){
      const dx = all[j].x-all[i].x, dy = all[j].y-all[i].y;
      pe -= G*all[i].m*all[j].m / Math.hypot(dx, dy);
    }
    return ke + pe;
  }

  // ---- Comets (test particles: feel gravity from every body, perturb nothing) ----
  function cometAccel(x, y){
    let ax = 0, ay = 0;
    for (const b of bodies){
      if (b.deleted) continue;
      const dx = b.x-x, dy = b.y-y, r2 = dx*dx + dy*dy + 1e-4;   // softened to avoid close-pass blowups
      const inv = G*b.m / (r2*Math.sqrt(r2));
      ax += inv*dx; ay += inv*dy;
    }
    return [ax, ay];
  }

  // Spacecraft feel the same bodies as comets but with a far sharper softening —
  // 1e-4 AU (15,000 km), below any planet's radius — so a flyby a few planet radii
  // out is real gravity, not a blur. k ∈ [0,1] interpolates each planet between its
  // pre- and post-step positions (set by stepAll), for sub-steps inside one DT.
  const PROBE_SOFT = 1e-8;
  function probeAccel(x, y, k){
    let ax = 0, ay = 0;
    for (const b of bodies){
      if (b.deleted) continue;
      const bx = b._px === undefined ? b.x : b._px + (b.x-b._px)*k, by = b._py === undefined ? b.y : b._py + (b.y-b._py)*k;
      const dx = bx-x, dy = by-y, r2 = dx*dx + dy*dy + PROBE_SOFT;
      const inv = G*b.m / (r2*Math.sqrt(r2));
      ax += inv*dx; ay += inv*dy;
    }
    return [ax, ay];
  }

  // ---- spacecraft targeting: Kepler propagation + a 2-body Lambert solver ----
  // Used once at launch to aim a transfer at where the target planet WILL be,
  // so a probe actually rendezvous instead of arriving at an empty orbit.
  // keplerProp: coast a body (Sun-only two-body) forward by dt, return [x,y].
  function keplerProp(body, dt){
    let x = body.x-SUN.x, y = body.y-SUN.y, vx = body.vx-SUN.vx, vy = body.vy-SUN.vy;
    const mu = G*SUN.m, h = DT, n = Math.max(1, Math.round(dt/h));
    for (let i=0;i<n;i++){
      let r = Math.hypot(x,y), a = -mu/(r*r*r), ax = a*x, ay = a*y;
      x += vx*h + 0.5*ax*h*h; y += vy*h + 0.5*ay*h*h;
      const r2 = Math.hypot(x,y), a2 = -mu/(r2*r2*r2);
      vx += 0.5*(ax + a2*x)*h; vy += 0.5*(ay + a2*y)*h;
    }
    return [x+SUN.x, y+SUN.y];
  }
  // lambertV: prograde single-revolution Lambert (universal variables). Given two
  // heliocentric position vectors and a time of flight, returns the departure
  // velocity (heliocentric). Null if degenerate.
  function lambertV(r1v, r2v, dt, mu, anyDir){
    const r1 = Math.hypot(r1v[0], r1v[1]), r2 = Math.hypot(r2v[0], r2v[1]);
    const cross = r1v[0]*r2v[1] - r1v[1]*r2v[0];
    // anyDir: take the short way round even when it sweeps clockwise (a course
    // correction from a probe already ahead of its target in longitude) — solve the
    // mirrored problem and mirror the velocity back
    if (anyDir && cross < 0){ const v = lambertV([r1v[0], -r1v[1]], [r2v[0], -r2v[1]], dt, mu, false); return v && [v[0], -v[1]]; }
    let dnu = Math.acos(Math.max(-1, Math.min(1, (r1v[0]*r2v[0]+r1v[1]*r2v[1])/(r1*r2))));
    if (cross < 0) dnu = 2*Math.PI - dnu;                        // enforce prograde (counter-clockwise) sweep
    const A = Math.sin(dnu)*Math.sqrt(r1*r2/(1-Math.cos(dnu)));
    if (!isFinite(A) || A === 0) return null;
    const Cf = z => z > 1e-6 ? (1-Math.cos(Math.sqrt(z)))/z : z < -1e-6 ? (Math.cosh(Math.sqrt(-z))-1)/(-z) : 0.5;
    const Sf = z => z > 1e-6 ? (Math.sqrt(z)-Math.sin(Math.sqrt(z)))/Math.sqrt(z*z*z)
                  : z < -1e-6 ? (Math.sinh(Math.sqrt(-z))-Math.sqrt(-z))/Math.sqrt(-z*-z*-z) : 1/6;
    const yOf = z => r1 + r2 + A*(z*Sf(z)-1)/Math.sqrt(Cf(z));
    // time of flight for a given z — NaN where y<0 (no physical arc there)
    const tof = z => { const y = yOf(z); if (!(y > 0)) return NaN; const c = Cf(z), chi = Math.sqrt(y/c); return (chi*chi*chi*Sf(z) + A*Math.sqrt(y))/Math.sqrt(mu); };
    // Time of flight rises monotonically with z across the single-revolution
    // domain (where y > 0), from 0 at the domain's lower edge to ∞ at z = 4π² — so
    // instead of scanning a grid for a sign change (which can step clean over the
    // domain when it is a sliver, e.g. a short, strongly hyperbolic hop between two
    // course corrections at 14 AU), find the lower edge by bisection on y, then
    // bisect for the time of flight. An unguarded Newton step from z = 0 used to
    // wander into y < 0 and hand back a NON-converged z as if it were a solution.
    const ZMAX = 4*Math.PI*Math.PI;                           // beyond this the arc is a multi-revolution transfer
    let lo = -ZMAX, hi = ZMAX*(1 - 1e-7);
    if (!(yOf(0) > 0)) return null;                            // no physical arc at all for this geometry
    if (!(yOf(lo) > 0)){                                       // the domain starts somewhere in (−4π², 0]: bisect y = 0
      let a = lo, b = 0;
      for (let i=0; i<200; i++){ const m = 0.5*(a+b); if (yOf(m) > 0) b = m; else a = m; }
      lo = b;
    }
    const tLo = tof(lo), tHi = tof(hi);
    if (!(isFinite(tLo)) || !(isFinite(tHi)) || dt < tLo || dt > tHi) return null;   // outside what a single-rev arc can do
    for (let it=0; it<200; it++){
      const mid = 0.5*(lo+hi), tm = tof(mid);
      if (!isFinite(tm)){ lo = mid; continue; }                // numerical edge of the domain: move in
      if (tm < dt) lo = mid; else hi = mid;
      if (hi-lo < 1e-14) break;
    }
    const z = 0.5*(lo+hi), tz = tof(z);
    if (!isFinite(tz) || Math.abs(tz-dt) > 1e-6*dt) return null;   // insist on a genuinely converged root
    const y = yOf(z), f = 1 - y/r1, g = A*Math.sqrt(y/mu);
    if (!isFinite(g) || g === 0) return null;
    return [ (r2v[0]-f*r1v[0])/g, (r2v[1]-f*r1v[1])/g ];
  }
  // bestTransfer: the cheapest direct transfer from Earth to `target` launching
  // NOW — one row of a real porkchop plot. Scans times of flight from 0.6× to
  // 1.3× the Hohmann time, solves Lambert for each, and trusts a root only after
  // re-flying it two-body to the aim point (a root that doesn't go there is
  // discarded). Returns { dv, dt, v1, aim, tT } — dv in AU/yr relative to Earth,
  // v1 the heliocentric departure velocity — or null if nothing fits.
  const TOF_SPAN = [0.6, 1.3], TOF_N = 16;
  function twoBodyStep(st, h, mu){                             // Verlet step of a [x,y,vx,vy] state about a fixed Sun
    let r = Math.hypot(st[0],st[1]), a = -mu/(r*r*r), ax = a*st[0], ay = a*st[1];
    st[0] += st[2]*h + 0.5*ax*h*h; st[1] += st[3]*h + 0.5*ay*h*h;
    const r2 = Math.hypot(st[0],st[1]), a2 = -mu/(r2*r2*r2);
    st[2] += 0.5*(ax + a2*st[0])*h; st[3] += 0.5*(ay + a2*st[1])*h;
  }
  function bestTransfer(target){
    const mu = G*SUN.m;
    const rE = [EARTH.x-SUN.x, EARTH.y-SUN.y], vex = EARTH.vx-SUN.vx, vey = EARTH.vy-SUN.vy;
    const r1 = Math.hypot(rE[0], rE[1]), r2 = Math.hypot(target.x-SUN.x, target.y-SUN.y);
    const at = (r1+r2)/2, tT = Math.PI*Math.sqrt(at*at*at/mu);
    const st = [target.x-SUN.x, target.y-SUN.y, target.vx-SUN.vx, target.vy-SUN.vy];   // the target, coasted once across the span
    const h = DT*4; let tp = 0, best = null;
    for (let k=0; k<=TOF_N; k++){
      const dt = tT*(TOF_SPAN[0] + (TOF_SPAN[1]-TOF_SPAN[0])*k/TOF_N);
      while (tp + h <= dt){ twoBodyStep(st, h, mu); tp += h; }
      if (dt - tp > 1e-12){ twoBodyStep(st, dt-tp, mu); tp = dt; }
      const v1 = lambertV(rE, [st[0], st[1]], dt, mu);
      if (!v1) continue;
      const dv = Math.hypot(v1[0]-vex, v1[1]-vey);
      if (best && dv >= best.dv) continue;
      const chk = [rE[0], rE[1], v1[0], v1[1]], n = 400, hc = dt/n;   // verify: does this root actually fly to the aim point?
      for (let i=0; i<n; i++) twoBodyStep(chk, hc, mu);
      if (Math.hypot(chk[0]-st[0], chk[1]-st[1]) > 0.015*r2) continue;
      best = { dv, dt, v1, aim: [st[0]+SUN.x, st[1]+SUN.y], tT };
    }
    return best;
  }

  // transferScan: like bestTransfer, but returns EVERY verified candidate across a
  // time-of-flight span (multiples of the Hohmann time), cheapest first. Daily Orbit
  // reads the whole curve (the "porkchop" strip) and re-flies the best few in the
  // N-body sim to find a par that the real physics can actually achieve.
  function transferScan(target, span, n){
    span = span || TOF_SPAN; n = n || TOF_N;
    const mu = G*SUN.m;
    const rE = [EARTH.x-SUN.x, EARTH.y-SUN.y], vex = EARTH.vx-SUN.vx, vey = EARTH.vy-SUN.vy;
    const r1 = Math.hypot(rE[0], rE[1]), r2 = Math.hypot(target.x-SUN.x, target.y-SUN.y);
    const at = (r1+r2)/2, tT = Math.PI*Math.sqrt(at*at*at/mu);
    const st = [target.x-SUN.x, target.y-SUN.y, target.vx-SUN.vx, target.vy-SUN.vy];
    const h = DT*4; let tp = 0; const out = [];
    for (let k=0; k<=n; k++){
      const dt = tT*(span[0] + (span[1]-span[0])*k/n);
      while (tp + h <= dt){ twoBodyStep(st, h, mu); tp += h; }
      if (dt - tp > 1e-12){ twoBodyStep(st, dt-tp, mu); tp = dt; }
      const v1 = lambertV(rE, [st[0], st[1]], dt, mu);
      if (!v1) continue;
      const chk = [rE[0], rE[1], v1[0], v1[1]], nn = 400, hc = dt/nn;
      for (let i=0; i<nn; i++) twoBodyStep(chk, hc, mu);
      if (Math.hypot(chk[0]-st[0], chk[1]-st[1]) > 0.015*r2) continue;
      const dv = Math.hypot(v1[0]-vex, v1[1]-vey), vArr = Math.hypot(chk[2]-st[2], chk[3]-st[3]);   // departure burn, two-body capture burn
      out.push({ dv, vArr, dt, v1, aim: [st[0]+SUN.x, st[1]+SUN.y], tT });
    }
    out.sort((a, b) => (a.dv + a.vArr) - (b.dv + b.vArr));
    return out;
  }

  // A course correction (what Voyager's small TCM burns did): the cheapest burn
  // that puts a spacecraft on a two-body arc from where it is to `target`'s
  // predicted position, `off` AU to the side of it (⟂ to the Sun–target line, +
  // = leading side). Times of flight are scanned around a straight-line guess and
  // each Lambert root is trusted only after re-flying it. Applies the burn and
  // returns { dv (AU/yr), tof, aim }, or null if nothing fits. tofGuess (years)
  // centres the scan on a known natural arrival time instead of the straight-line guess.
  function probeCorrection(pr, target, off, tofGuess){
    const mu = G*SUN.m;
    const rP = [pr.x-SUN.x, pr.y-SUN.y], vP = [pr.vx-SUN.vx, pr.vy-SUN.vy];
    const guess = tofGuess > 0 ? tofGuess : Math.hypot(target.x-pr.x, target.y-pr.y)/(Math.hypot(vP[0], vP[1]) || 1e-9);
    const st = [target.x-SUN.x, target.y-SUN.y, target.vx-SUN.vx, target.vy-SUN.vy];
    // the burn for a given time of flight (target coasted two-body to that moment, aim
    // offset to the side, Lambert, re-fly check); null if no verified arc
    const at = tof => {
      const st = [target.x-SUN.x, target.y-SUN.y, target.vx-SUN.vx, target.vy-SUN.vy], h = DT*4; let tp = 0;
      while (tp + h <= tof){ twoBodyStep(st, h, mu); tp += h; }
      if (tof - tp > 1e-12) twoBodyStep(st, tof-tp, mu);
      const r2 = Math.hypot(st[0], st[1]), aim = [st[0] - st[1]/r2*off, st[1] + st[0]/r2*off];
      const v1 = lambertV(rP, aim, tof, mu, true); if (!v1) return null;
      const chk = [rP[0], rP[1], v1[0], v1[1]], n = 400, hc = tof/n;
      for (let i=0; i<n; i++) twoBodyStep(chk, hc, mu);
      if (Math.hypot(chk[0]-aim[0], chk[1]-aim[1]) > 0.01*r2) return null;
      return { dv: Math.hypot(v1[0]-vP[0], v1[1]-vP[1]), tof, v1, aim: [aim[0]+SUN.x, aim[1]+SUN.y] };
    };
    // coarse scan of times of flight, then a golden-section refinement around the
    // cheapest — the burn is exquisitely sensitive to matching the natural arrival
    // time (a grid alone left 150 m/s "corrections" that were really grid error)
    let best = null, kb = -1;
    for (let k=0; k<=30; k++){ const c = at(guess*(0.55 + 1.2*k/30)); if (c && (!best || c.dv < best.dv)){ best = c; kb = k; } }
    if (!best) return null;
    let a = guess*(0.55 + 1.2*Math.max(0, kb-1)/30), b = guess*(0.55 + 1.2*Math.min(30, kb+1)/30);
    const gr = (Math.sqrt(5)-1)/2; let x1 = b - gr*(b-a), x2 = a + gr*(b-a), f1 = at(x1), f2 = at(x2);
    for (let i=0; i<40; i++){
      const d1 = f1 ? f1.dv : Infinity, d2 = f2 ? f2.dv : Infinity;
      if (d1 < d2){ b = x2; x2 = x1; f2 = f1; x1 = b - gr*(b-a); f1 = at(x1); } else { a = x1; x1 = x2; f1 = f2; x2 = a + gr*(b-a); f2 = at(x2); }
      const c = d1 < d2 ? f1 : f2; if (c && c.dv < best.dv) best = c;
    }
    pr.vx = SUN.vx + best.v1[0]; pr.vy = SUN.vy + best.v1[1];
    return best;
  }

  // semi-major axis of o's two-body orbit about pref (negative ⇒ unbound) — same math the HUD table uses
  function aOf(o, pref){
    const dx = o.x-pref.x, dy = o.y-pref.y, r = Math.hypot(dx, dy);
    const vx = o.vx-pref.vx, vy = o.vy-pref.vy;
    return 1 / (2/r - (vx*vx + vy*vy)/(G*pref.m));
  }

  // inelastic merge: b survives, absorbing c's mass and momentum (momentum-conserving)
  function mergeInto(b, c){
    const M = b.m + c.m;
    b.vx = (b.m*b.vx + c.m*c.vx)/M;
    b.vy = (b.m*b.vy + c.m*c.vy)/M;
    b.m = M;
  }

  // a comet/interloper reached a body — decide who survives, narrate it, kick off effects
  function resolveImpact(c, b){
    const kms = Math.hypot(c.vx-b.vx, c.vy-b.vy) * KMS;
    const big = b.sun || c.m > 1e-5 || b.m > 1e-4;
    if (!b.sun && c.m >= b.m){                     // the interloper wins — the planet/moon is consumed
      mergeInto(c, b);
      b.deleted = true;
      if (b === EARTH) MOON.deleted = true;        // a Moon with no Earth makes no sense
      EMIT('consumed', { name: c.name, target: b.name });
      flashes.push({ x: b.x, y: b.y, life: 1, big: true });
      FX('impact', { x: b.x, y: b.y, vx: c.vx, vy: c.vy, big: true, sun: false });
    } else {                                       // the body absorbs the impactor (the Sun always wins)
      mergeInto(b, c);
      c.dead = true;
      if (!b.sun) b._glow = 1;                     // brief impact glow on the struck body
      EMIT('impact', { name: c.name, target: b.name, kms, big });
      flashes.push({ x: c.x, y: c.y, life: 1, big });
      FX('impact', { x: c.x, y: c.y, vx: c.vx, vy: c.vy, big, sun: !!b.sun });
    }
    E0 = energy();                                 // any merge changes the conserved baseline
  }

  // Auto-timewarp: a comet spawns 22 AU out, which is minutes of empty approach at
  // normal speed. While every live comet is far out and at least one is inbound,
  // time compresses; it snaps back the moment anything crosses 8 AU.
  function warpFactor(){
    if (timeRate <= 0) return 1;
    let nearest = Infinity, inbound = false;
    for (const c of comets){
      if (c.dead) continue;
      const dx = c.x-SUN.x, dy = c.y-SUN.y, r = Math.hypot(dx, dy);
      if (r < nearest) nearest = r;
      if (dx*(c.vx-SUN.vx) + dy*(c.vy-SUN.vy) < 0) inbound = true;
    }
    if (nearest === Infinity || nearest <= 8 || !inbound) return 1;
    return timeRate >= 16 ? 4 : 8;                 // gentler multiplier when already running fast
  }

  // Event detection — runs every 0.01 sim-years (not per frame), with hysteresis
  // counted in passes so one wild frame during a close encounter can't false-fire.
  function detectPass(){
    // Sun-relative detectors (ejections, captures) are meaningless without a
    // Sun — with it deleted there's no "system" to leave or join.
    if (!SUN.deleted)
    for (const p of planets){
      if (p.deleted) continue;
      if (aOf(p, SUN) <= 0){                                   // unbound from the Sun
        p._reb = 0;
        if (!p._ejected && ++p._ub === 30){ p._ejected = true; EMIT('eject', { name: p.name }); }  // ~0.3 yr sustained
      } else {                                                 // bound again
        p._ub = 0;
        // A slingshot flickers a planet across the bound/unbound line many times;
        // the _ejected latch stops it re-announcing on every crossing. Only a
        // sustained recapture (~0.6 yr bound) clears it, so a genuine later
        // ejection can still report.
        if (p._ejected && ++p._reb >= 60){ p._ejected = false; p._reb = 0; }
      }
    }
    if (!MOON.deleted && !EARTH.deleted && !MOON._torn){
      if (aOf(MOON, EARTH) <= 0){ if (++MOON._ubE >= 20){ MOON._torn = true; EMIT('moontorn', {}); } }
      else MOON._ubE = 0;
    }
    if (!SUN.deleted)
    for (const c of comets){
      if (c.dead) continue;
      const a = aOf(c, SUN);
      if (a > 0 && a < 40){                        // bound, and not a formality like a 300-AU "orbit"
        c._ubC = 0;
        if (!c._cap && ++c._bd === 40){            // ~0.4 yr sustained → a real capture, not a flicker
          c._cap = true;
          EMIT('capture', { name: c.name, T: 2*Math.PI*Math.sqrt(a*a*a/(G*SUN.m)) });
        }
      } else {
        c._bd = 0;
        if (c._cap && ++c._ubC >= 40){ c._cap = false; c._ubC = 0; EMIT('flung', { name: c.name }); }
      }
    }
  }

  // One rendered frame's worth of physics: `sub` substeps for the real actors
  // (bodies + comets, with per-substep collision checks), a capped number of
  // coarser substeps for the decorative specks (storm + belt), then trails,
  // culling, and the detector cadence.
  function advance(sub, dir){
    const dt = dir < 0 ? -DT : DT;
    for (let s = 0; s < sub; s++){
      stepAll(dt); t += dt;
      for (const c of comets){
        if (c.dead) continue;
        let [ax, ay] = cometAccel(c.x, c.y);
        c.x += c.vx*dt + 0.5*ax*dt*dt; c.y += c.vy*dt + 0.5*ay*dt*dt;
        const [ax2, ay2] = cometAccel(c.x, c.y);
        c.vx += 0.5*(ax+ax2)*dt; c.vy += 0.5*(ay+ay2)*dt;
        // collide check EVERY sub-step — a fast Sun-grazer slips past a once-per-frame check
        for (const b of bodies){
          if (b.deleted) continue;
          const hr = (b.sun ? 0.05 : 0.02) + (c.m > 1e-3 ? 0.03 : 0), ex = b.x-c.x, ey = b.y-c.y;
          if (ex*ex + ey*ey < hr*hr){ resolveImpact(c, b); break; }
        }
      }
      // spacecraft: full-fidelity test particles (few, and need accuracy for a
      // rendezvous) — stepped every substep alongside the comets, with a
      // per-substep closest-approach so a fast probe can't tunnel past its target.
      for (const pr of probes){
        if (pr.done) continue;
        // A Voyager-class flyby passes a few planet radii out at ~40 km/s — one
        // 1.75-hour step would jump straight through it. Near the closest massive
        // body the step is split so each piece moves the probe at most 2% of its
        // distance to that body (≈40 pieces at Voyager's Jupiter periapsis, 1 on
        // the cruise), with the planets interpolated across the pieces.
        let near = null, nd2 = Infinity;
        for (const b of bodies){ if (b.deleted || b.m < 1e-7) continue; const ex = b.x-pr.x, ey = b.y-pr.y, d2 = ex*ex + ey*ey; if (d2 < nd2){ nd2 = d2; near = b; } }
        let n = 1;
        if (near){ const d = Math.sqrt(nd2), vr = Math.hypot(pr.vx-near.vx, pr.vy-near.vy) + 1e-9; n = Math.min(512, Math.max(1, Math.ceil(Math.abs(dt)*vr/(0.02*d)))); }
        const h = dt/n, tb = pr.target;
        if (!pr.minD) pr.minD = {};                     // closest approach to every planet passed — flyby narration reads it
        for (let s = 0; s < n; s++){
          const [ax, ay] = probeAccel(pr.x, pr.y, s/n);
          pr.x += pr.vx*h + 0.5*ax*h*h; pr.y += pr.vy*h + 0.5*ay*h*h;
          const [ax2, ay2] = probeAccel(pr.x, pr.y, (s+1)/n);
          pr.vx += 0.5*(ax+ax2)*h; pr.vy += 0.5*(ay+ay2)*h;
          if (near){
            const k = (s+1)/n, bx = near._px + (near.x-near._px)*k, by = near._py + (near.y-near._py)*k, d = Math.hypot(pr.x-bx, pr.y-by);
            if (!(d >= pr.minD[near.name])) pr.minD[near.name] = d;
            if (near === tb){ if (d < pr.closest){ pr.closest = d; pr.tClose = t; pr.vRel = Math.hypot(pr.vx-near.vx, pr.vy-near.vy); } if (d < (pr.arrR || 0.05) && !pr.arrived){ pr.arrived = true; pr.tArr = t; pr.vArr = Math.hypot(pr.vx-near.vx, pr.vy-near.vy); } }
            if (d < (near.R || 0)){ pr.crashed = near.name; pr.done = true; EMIT('probelost', { target: near.name }); break; }
          }
        }
        if (pr.done) continue;
        if (tb && !tb.deleted && tb !== near){
          const d = Math.hypot(pr.x-tb.x, pr.y-tb.y);
          if (d < pr.closest){ pr.closest = d; pr.tClose = t; pr.vRel = Math.hypot(pr.vx-tb.vx, pr.vy-tb.vy); }
          if (d < (pr.arrR || 0.05) && !pr.arrived){ pr.arrived = true; pr.tArr = t; pr.vArr = Math.hypot(pr.vx-tb.vx, pr.vy-tb.vy); }   // arrival radius scales with the target's sphere of influence
        }
      }
    }
    // specks: same physics, capped substeps (belt + a full storm at ×32 would be
    // ~5× the whole frame budget if stepped at full fidelity — they're decorative)
    const sCap = Math.min(sub, 16), dtS = dt * (sub / sCap);
    for (let s = 0; s < sCap; s++){
      for (const arr of [storm, belt]){
        for (const c of arr){
          if (c.dead) continue;
          let [ax, ay] = cometAccel(c.x, c.y);
          c.x += c.vx*dtS + 0.5*ax*dtS*dtS; c.y += c.vy*dtS + 0.5*ay*dtS*dtS;
          const [ax2, ay2] = cometAccel(c.x, c.y);
          c.vx += 0.5*(ax+ax2)*dtS; c.vy += 0.5*(ay+ay2)*dtS;
          for (const b of bodies){
            if (b.deleted) continue;
            const hr = b.sun ? 0.05 : 0.02, ex = b.x-c.x, ey = b.y-c.y;
            if (ex*ex + ey*ey < hr*hr){ c.dead = true; flashes.push({x:b.x, y:b.y, life:1, big:b.sun}); break; }
          }
        }
      }
    }
    // trails (one point per rendered frame, as before)
    for (const p of planets){ if (!p.deleted){ p.trail.push({x:p.x, y:p.y}); if (p.trail.length > 600) p.trail.shift(); } }
    if (!MOON.deleted && !EARTH.deleted){ MOON.rel.push({dx: MOON.x-EARTH.x, dy: MOON.y-EARTH.y}); if (MOON.rel.length > 90) MOON.rel.shift(); }
    for (const c of comets){ if (!c.dead){ c.trail.push({x:c.x, y:c.y}); if (c.trail.length > 500) c.trail.shift(); } }
    for (const pr of probes){ if (!pr.done){ pr.trail.push({x:pr.x, y:pr.y}); if (pr.trail.length > 900) pr.trail.shift(); } }
    probes = probes.filter(pr => !pr.done);
    const nC = comets.length;
    comets = comets.filter(c => {
      if (c.dead) return false;
      if (Math.hypot(c.x-baryX, c.y-baryY) > 80){ EMIT('escape', { name: c.name }); return false; }
      return true;
    });
    if (comets.length !== nC) E0 = energy();       // re-baseline after any removal
    for (const c of storm){ if (!c.dead){ c.trail.push({x:c.x, y:c.y}); if (c.trail.length > 14) c.trail.shift(); } }
    storm = storm.filter(c => !c.dead && Math.hypot(c.x-baryX, c.y-baryY) <= 80);   // no energy re-baseline: massless
    belt = belt.filter(c => !c.dead && Math.hypot(c.x-baryX, c.y-baryY) <= 12);     // flung belt rock: quietly gone
    for (const f of flashes) f.life -= 0.05;
    flashes = flashes.filter(f => f.life > 0);
    detAcc += sub*DT;
    if (detAcc >= 0.01){ detectPass(); detAcc = 0; }
  }
  
  return {
    G, DT, KMS, SUN, planets, EARTH, MOON, bodies,
    reset, advance, energy, keplerProp, lambertV, bestTransfer, transferScan, probeCorrection,
    arrangeForDate, elementsAt, julianDay, JD_J2000,
    addProbe: p => { probes.push(p); return p; },
    clearProbes: () => { probes.length = 0; },
    clearSpecks: () => { belt.length = 0; storm.length = 0; },
    state: () => ({ t, comets, belt, storm, probes, E0 }),
    setRate: r => { timeRate = r; },
    onEmit: f => { EMIT = f; },
    onFx: f => { FX = f; }
  };
}
if (typeof module !== 'undefined' && module.exports) module.exports = { createSolarCore };
