import {W,H,R,DT,HOLES,createBall,movingWall,shoot,speed,step,simulate} from './physics.mjs';
const $=id=>document.getElementById(id),canvas=$('course'),ctx=canvas.getContext('2d');
let index=0,h=HOLES[0],ball=createBall(h),strokes=0,scores=Array(9).fill(null),practice=false,state='menu',angle=-Math.PI/2,power=.45,drag=null,time=0,acc=0,last=0,shotOrigin={...h.start},trail=[],particles=[],best=null,rounds=0,sound=false,audio=null,lastTone=0,returnState='ready',newRecord=false;
try{const save=JSON.parse(localStorage.getItem('miniGolfRecord'));if(save&&Number.isInteger(save.best)&&save.best>=9&&save.best<=108)best=save.best;rounds=save?.rounds||0;}catch{}
$('best').textContent=best===null?'—':best+' shots';
for(let i=0;i<9;i++){const o=document.createElement('option');o.value=i;o.textContent=`${i+1}. ${HOLES[i].name}`;$('practice-hole').append(o);}
function resize(){const w=$('viewport').parentElement.clientWidth;const scale=Math.min(1,w/W,Math.max(280,innerHeight-215)/H);$('stage').style.transform=`scale(${scale})`;$('viewport').style.width=W*scale+'px';$('viewport').style.height=H*scale+'px';}
addEventListener('resize',resize);new ResizeObserver(resize).observe($('viewport').parentElement);resize();
function tone(freq,duration=.08,type='sine',volume=.035){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function status(s){$('status').textContent=s;}
function update(){ $('hole').textContent=String(index+1).padStart(2,'0')+' / 09';$('par').textContent=h.par;$('strokes').textContent=strokes;$('hole-name').textContent=h.name;$('tip').textContent=h.tip;$('mode').textContent=practice?'PRACTICE · NOT RANKED':'THE SCORECARD';const delta=scores.reduce((n,s,i)=>n+(s===null?0:s-HOLES[i].par),0);$('total').textContent=practice?'—':delta===0?'E':delta>0?'+'+delta:delta;$('scorecard').innerHTML=HOLES.map((a,i)=>`<li class="${i===index?'current':''}"><span>${String(i+1).padStart(2,'0')}</span><span>${a.name}</span><small>PAR ${a.par}</small><b>${scores[i]??'–'}</b></li>`).join('');$('pause').disabled=!['ready','rolling','paused'].includes(state);$('restart').disabled=!['ready','rolling','paused'].includes(state);$('power-meter').style.width=power*100+'%';}
function panel(label,title,copy,primary,action,secondary,second){$('panel-label').textContent=label;$('panel-title').textContent=title;$('panel-copy').textContent=copy;$('primary').textContent=primary;$('primary').onclick=action;$('practice-controls').hidden=true;$('secondary').hidden=!secondary;$('secondary').textContent=secondary||'';$('secondary').onclick=second||null;$('overlay').hidden=false;$('primary').focus({preventScroll:true});}
function tee(i){index=i;h=HOLES[i];ball=createBall(h);strokes=0;time=0;lastTone=0;acc=0;trail=[];particles=[];angle=Math.atan2(h.cup.y-ball.y,h.cup.x-ball.x);power=.45;state='ready';drag=null;$('overlay').hidden=true;canvas.focus({preventScroll:true});status(practice?'Practice hole. Drag back to putt.':'Drag back to aim. Release to putt.');update();}
function start(isPractice=false){practice=isPractice;scores=Array(9).fill(null);newRecord=false;tee(isPractice?Number($('practice-hole').value):0);}
function menu(){state='menu';drag=null;panel('THE NIGHT COURSE','A little touch. A better round.','Nine holes. Glowing rails. One ball. Pull back to aim, release to putt.','Play nine holes →',()=>start());$('practice-controls').hidden=false;status('Your first tee is waiting.');update();}
$('primary').onclick=()=>start();$('practice').onclick=()=>start(true);
function finish(capped=false){if(state!=='rolling')return;state='result';status(capped?'Hole picked up at the stroke limit.':'In the cup!');scores[index]=strokes;drag=null;update();const diff=strokes-h.par;const title=capped?'Stroke limit':strokes===1?'Hole in one!':diff<=-2?'Eagle!':diff===-1?'Birdie!':diff===0?'Right on par.':diff===1?'Bogey.':'In the cup.';if(!capped){for(let i=0;i<35;i++)particles.push({x:ball.x,y:ball.y,vx:(Math.random()-.5)*180,vy:-Math.random()*150,life:1.4,color:i%2?'#64eadb':'#ffc76e'});tone(660,.2);setTimeout(()=>tone(880,.3),130);}
if(practice){panel('PRACTICE COMPLETE',title,`${strokes} ${strokes===1?'stroke':'strokes'} · Par ${h.par}. Practice scores do not affect your record.`,'Try this hole again',()=>tee(index),'Choose a different hole',menu);return;}
if(index===8){const total=scores.reduce((a,b)=>a+b,0);newRecord=best===null||total<best;rounds++;if(newRecord)best=total;try{localStorage.setItem('miniGolfRecord',JSON.stringify({best,rounds}));}catch{status('Round finished. Browser storage is unavailable.');}$('best').textContent=best+' shots';const result=total-29;panel(newRecord?'NEW PERSONAL BEST':'ROUND COMPLETE',`${total} strokes`,`${result===0?'Even par':result>0?result+' over par':-result+' under par'} across nine holes. ${capped?'Final hole picked up at the stroke limit.':'The clubhouse is yours.'}`,'Play another round →',()=>start(),'Back to clubhouse',menu);
}else panel(`HOLE ${index+1} COMPLETE`,title,`${strokes} ${strokes===1?'stroke':'strokes'} · Par ${h.par}${capped?' · Picked up after 12 strokes.':''}`,`Next: ${HOLES[index+1].name} →`,()=>tee(index+1));}
function putt(){if(state!=='ready'||power<.025)return;shotOrigin={x:ball.x,y:ball.y};if(!shoot(ball,angle,power))return;strokes++;state='rolling';trail=[];tone(190,.08,'triangle');status('Ball in motion…');update();}
function togglePause(){if(state==='paused'){state=returnState;$('overlay').hidden=true;canvas.focus({preventScroll:true});status(state==='ready'?'Drag back to aim. Release to putt.':'Ball in motion…');}else if(['ready','rolling'].includes(state)){returnState=state;state='paused';drag=null;panel('TAKE YOUR TIME','Round paused','Your ball will be right where you left it.','Resume →',togglePause);}update();}
$('pause').onclick=togglePause;$('restart').onclick=()=>{if(['menu','confirm'].includes(state))return;const prev=state;state='confirm';drag=null;panel('NEW ROUND','Start fresh?', 'Your current round will be discarded. Your best score stays saved.','Start a new round',()=>start(),'Keep playing',()=>{state=prev;if(prev==='result'){state='rolling';finish(strokes>=12&&!ball.sunk);}else if(prev==='paused'){state=returnState;togglePause();}else $('overlay').hidden=true;update();});update();};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));tone(440);};
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
canvas.addEventListener('pointerdown',e=>{if(state!=='ready'||(e.pointerType==='mouse'&&e.button!==0)||drag)return;e.preventDefault();canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);drag={...point(e),id:e.pointerId};power=0;update();});
canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const p=point(e),dx=drag.x-p.x,dy=drag.y-p.y;power=Math.min(1,Math.hypot(dx,dy)/160);if(power>.015)angle=Math.atan2(dy,dx);status(`Power ${Math.round(power*100)}% · release to putt`);$('power-meter').style.width=power*100+'%';});
canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(power>=.025)putt();else{power=.45;status('Shot cancelled. Drag back to aim.');update();}});
for(const event of ['pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>{if(drag){drag=null;power=.45;status('Shot cancelled.');update();}});
addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName))return;if(e.key.toLowerCase()==='m'){$('sound').click();return;}if(e.key.toLowerCase()==='p'){e.preventDefault();togglePause();return;}if(state!=='ready')return;const fine=e.shiftKey?.25:1;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')angle-=.065*fine;if(e.key==='ArrowRight')angle+=.065*fine;if(e.key==='ArrowUp')power=Math.min(1,power+.03*fine);if(e.key==='ArrowDown')power=Math.max(.03,power-.03*fine);if(e.key===' '&&!e.repeat)putt();else if(e.key.startsWith('Arrow')){status(`Power ${Math.round(power*100)}% · Space to putt`);update();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&['ready','rolling'].includes(state))togglePause();});
function roundRect(x,y,w,ht,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,ht,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function circle(x,y,r,color){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function text(s,x,y,color,size=12){ctx.fillStyle=color;ctx.font=`600 ${size}px Inter, sans-serif`;ctx.fillText(s,x,y);}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#0d1725';ctx.fillRect(0,0,W,H);ctx.shadowBlur=18;ctx.shadowColor='#64eadb55';roundRect(26,26,548,588,22,'#113c39','#55cdbb');ctx.shadowBlur=0;ctx.save();ctx.beginPath();ctx.roundRect(33,33,534,574,17);ctx.clip();for(let y=30;y<610;y+=36){ctx.fillStyle=(y/36|0)%2?'#ffffff03':'#00000006';ctx.fillRect(30,y,540,36);}for(let x=50;x<560;x+=32)for(let y=50;y<600;y+=32)circle(x,y,1,'#74dbbb10');
for(const a of h.sand){roundRect(a.x,a.y,a.w,a.h,18,'#b49760');for(let x=a.x+8;x<a.x+a.w;x+=15)for(let y=a.y+8;y<a.y+a.h;y+=15)circle(x+(y%3),y,1,'#715f37');text('SAND',a.x+12,a.y+22,'#584926',10);}
for(const a of h.water){roundRect(a.x,a.y,a.w,a.h,8,'#104d73','#419bb9');ctx.strokeStyle='#75dbef44';for(let y=a.y+10;y<a.y+a.h;y+=15){ctx.beginPath();for(let x=a.x;x<=a.x+a.w;x+=5){const yy=y+Math.sin(x*.06+time*2)*3;x===a.x?ctx.moveTo(x,yy):ctx.lineTo(x,yy);}ctx.stroke();}text('WATER',a.x+12,a.y+20,'#88ddf2',10);}
for(const a of h.slopes){roundRect(a.x,a.y,a.w,a.h,10,'#58447744');for(let x=a.x+25;x<a.x+a.w;x+=45)for(let y=a.y+25;y<a.y+a.h;y+=42){ctx.strokeStyle='#c0a5fc55';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-7,y-6);ctx.lineTo(x,y);ctx.lineTo(x-7,y+6);ctx.stroke();}text('CROSS CURRENT →',a.x+12,a.y+17,'#c9b6fc',10);}
for(const a of h.ramps){roundRect(a.x,a.y,a.w,a.h,7,'#916c33','#ffc76e');for(let x=a.x+18;x<a.x+a.w;x+=25){ctx.strokeStyle='#ffdb98';ctx.beginPath();ctx.moveTo(x-7,a.y+29);ctx.lineTo(x,a.y+19);ctx.lineTo(x+7,a.y+29);ctx.stroke();}text('JUMP',a.x+46,a.y+12,'#ffe4ba',9);}
for(const a of [...h.walls,...(h.gate?[movingWall(h,time)]:[])]){ctx.shadowColor='#9576e766';ctx.shadowBlur=12;roundRect(a.x,a.y+5,a.w,a.h,5,'#070e1c');roundRect(a.x,a.y,a.w,a.h,5,'#333551','#bca5f3');ctx.shadowBlur=0;ctx.fillStyle='#ffffff20';ctx.fillRect(a.x+5,a.y+3,a.w-10,3);}
for(const a of h.bumpers){circle(a.x+2,a.y+5,a.r+3,'#061d25');ctx.shadowColor='#eeb66d';ctx.shadowBlur=12;circle(a.x,a.y,a.r,'#ffc76e');ctx.shadowBlur=0;circle(a.x,a.y,a.r-5,'#80592d');circle(a.x,a.y,a.r-9,'#c69853');circle(a.x-7,a.y-7,5,'#ffde9b');}
ctx.strokeStyle='#64eadb55';ctx.lineWidth=1;ctx.beginPath();ctx.arc(h.start.x,h.start.y,14,0,Math.PI*2);ctx.stroke();text('TEE',h.start.x-10,h.start.y+31,'#69ac9a',9);
ctx.shadowColor='#64eadb';ctx.shadowBlur=13;circle(h.cup.x,h.cup.y,13,'#55c9ac');ctx.shadowBlur=0;circle(h.cup.x,h.cup.y,10,'#050d18');circle(h.cup.x+2,h.cup.y+3,5,'#000');ctx.strokeStyle='#d7dbe2';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(h.cup.x+2,h.cup.y-3);ctx.lineTo(h.cup.x+2,h.cup.y-44);ctx.stroke();ctx.fillStyle='#ffc76e';ctx.beginPath();ctx.moveTo(h.cup.x+3,h.cup.y-44);ctx.lineTo(h.cup.x+31,h.cup.y-35);ctx.lineTo(h.cup.x+3,h.cup.y-25);ctx.fill();text(String(index+1),h.cup.x+9,h.cup.y-32,'#553e25',10);
if(state==='ready'&&power>.025){const preview=simulate(h,ball,angle,power,time,110).path;ctx.strokeStyle='#d8fff277';ctx.lineWidth=2;ctx.setLineDash([3,8]);ctx.beginPath();ctx.moveTo(ball.x,ball.y);for(const p of preview)ctx.lineTo(p.x,p.y);ctx.stroke();ctx.setLineDash([]);const p=preview.at(-1);if(p)circle(p.x,p.y,3,'#ccfff3');}
trail.forEach((p,i)=>circle(p.x,p.y,2+(i/trail.length)*2,`rgba(171,237,255,${i/trail.length*.23})`));
if(!ball.sunk){const lift=ball.air?Math.sin(Math.PI*ball.air/.75)*24:0;circle(ball.x+3,ball.y+5,7,'#00141477');const g=ctx.createRadialGradient(ball.x-3,ball.y-lift-3,1,ball.x,ball.y-lift,10);g.addColorStop(0,'#ffffff');g.addColorStop(1,'#9dbdcc');circle(ball.x,ball.y-lift,R+(lift/12),g);circle(ball.x-2,ball.y-lift-2,1,'#ffffff');}
for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/1.4);circle(p.x,p.y,3,p.color);}ctx.globalAlpha=1;ctx.restore();}
function frame(now){const delta=Math.min((now-last)/1000||0,.05);last=now;if(['ready','rolling'].includes(state)){acc+=delta;while(acc>=DT){time+=DT;acc-=DT;if(state==='rolling'){const e=step(ball,h,time);if(e==='water'){strokes=Math.min(12,strokes+1);ball={...createBall(h),...shotOrigin};tone(95,.2);if(strokes>=12)finish(true);else{state='ready';angle=Math.atan2(h.cup.y-ball.y,h.cup.x-ball.x);status('Water! +1 penalty. Back at your last position.');update();}}else if(e==='sunk')finish();else if(e==='rest'){if(strokes>=12)finish(true);else{state='ready';status('Your shot. Drag back to aim.');update();}}else if(e==='jump'){tone(480,.14);status('Airborne!');}else if((e==='bounce'||e==='bumper')&&time-lastTone>.08){lastTone=time;tone(e==='bumper'?520:260,.05);}if(state==='rolling'){trail.push({x:ball.x,y:ball.y});if(trail.length>18)trail.shift();}}}}
for(const p of particles){p.x+=p.vx*delta;p.y+=p.vy*delta;p.vy+=180*delta;p.life-=delta;}particles=particles.filter(p=>p.life>0);draw();requestAnimationFrame(frame);}
update();requestAnimationFrame(frame);
