// Authored opening course. # bedrock, * breakable rock, . floor, S linked
// shaft, E exit, b bat, k knocker, f fireball, i ignitor, + bomb capacity.
// Enemies and pickups occupy floor; hidden rewards are listed separately.
export const OPENING_LEVELS = [
  {
    name: 'First Blast',
    hint: 'Space: plant a bomb, then step around a corner.',
    rows: [
      '#############',
      '#...*.......#',
      '#.#.#.#.#.#.#',
      '#...*...b...#',
      '###.#.###.#.#',
      '#...*.......#',
      '#.#.###.#.#.#',
      '#.....*...b.#',
      '#.#.#.#.#.#.#',
      '#.....*....E#',
      '#############',
    ],
    rewards: [{x:4,y:3,type:'bomb'}, {x:6,y:7,type:'fire'}],
  },
  {
    name: 'Connected Shafts',
    hint: 'Bomb ON a shaft to blast every shaft. Step two tiles clear.',
    rows: [
      '#############',
      '#..S.*......#',
      '#.#..#..#.#.#',
      '#....*..Sb..#',
      '#....#......#',
      '##*#####*####',
      '#....#......#',
      '#....*..Sb..#',
      '#.#..#..#.#.#',
      '#....*.....E#',
      '#############',
    ],
    rewards: [{x:5,y:3,type:'fire'}, {x:8,y:5,type:'radiation'}],
  },
  {
    name: 'Fireball Gallery',
    hint: 'Collect the orange flask. Face a creature and press F.',
    rows: [
      '#############',
      '#...*......b#',
      '#f#.#.###.#.#',
      '#...*.......#',
      '#.#.#.#.#.#.#',
      '#...S...S.k.#',
      '#.#.#.#.#.#.#',
      '#...*......b#',
      '#.#.###.#.#.#',
      '#.......*..E#',
      '#############',
    ],
    rewards: [{x:4,y:3,type:'fireball'}, {x:8,y:9,type:'bomb'}],
  },
  {
    name: 'Fuse Workshop',
    hint: 'Collect +bomb and the purple ignitor. F fires a planted bomb early.',
    rows: [
      '#############',
      '#.+S.*.....b#',
      '#.#..#..#.#.#',
      '#i...*......#',
      '##*###..#.#.#',
      '#....S..*..k#',
      '#.#..#..###.#',
      '#....*......#',
      '#.#..#..#.#.#',
      '#...b*..S..E#',
      '#############',
    ],
    rewards: [{x:5,y:3,type:'bomb'}, {x:8,y:5,type:'radiation'}, {x:5,y:7,type:'fire'}],
  },
  {
    name: 'The Proving Ground',
    hint: 'They dodge blasts now. Use shafts and corners to set a trap.',
    rows: [
      '#############',
      '#..S.*......#',
      '#f#..#..#.#.#',
      '#....*..S.k.#',
      '#.#.###.*.#.#',
      '#...*...*...#',
      '#.*.###.#.#.#',
      '#.b.S...*...#',
      '#.#.*.#.#.#.#',
      '#...*k..S..E#',
      '#############',
    ],
    rewards: [{x:5,y:3,type:'bomb'}, {x:8,y:5,type:'ignitor'}, {x:4,y:8,type:'radiation'}, {x:8,y:7,type:'fire'}],
  },
];
