// Authored opening course. # bedrock, * breakable rock, . floor, S linked
// shaft, E exit, b bat, k knocker, f flare launcher, i blasting plunger, + bomb capacity.
// Enemies and pickups occupy floor; hidden rewards are listed separately.
export const OPENING_LEVELS = [
  {
    name: 'Collapsed Gallery',
    hint: 'Space: blast a path through the cave-in. Retreat around a corner.',
    rows: [
      '#############',
      '#...*..**...#',
      '#.#.#.#.#.#.#',
      '#...*...b.*.#',
      '###.#.###.#.#',
      '#.*.*..*..*.#',
      '#.#.###.#.#.#',
      '#...*.*...b.#',
      '#.#.#.#.#.#.#',
      '#..**.*..b.E#',
      '#############',
    ],
    rewards: [
      { x: 4, y: 3, type: 'bomb' },
      { x: 6, y: 7, type: 'fire' },
    ],
  },
  {
    name: 'Connected Shafts',
    hint: 'Bomb ON a shaft to blast every shaft. Step two tiles clear.',
    rows: [
      '#############',
      '#..S.*......#',
      '#.#..#..#.#.#',
      '#....*..Sb..#',
      '#....#......#',
      '##*#####*####',
      '#....#......#',
      '#....*..Sb..#',
      '#.#..#..#.#.#',
      '#....*.....E#',
      '#############',
    ],
    rewards: [
      { x: 5, y: 3, type: 'fire' },
      { x: 8, y: 5, type: 'shield' },
    ],
  },
  {
    name: 'Flare Gallery',
    hint: 'Collect the flare launcher. Face a creature and press F.',
    rows: [
      '#############',
      '#...*......b#',
      '#f#.#.###.#.#',
      '#...*.......#',
      '#.#.#.#.#.#.#',
      '#...S...S.k.#',
      '#.#.#.#.#.#.#',
      '#...*......b#',
      '#.#.###.#.#.#',
      '#.......*..E#',
      '#############',
    ],
    rewards: [
      { x: 4, y: 3, type: 'fireball' },
      { x: 8, y: 9, type: 'bomb' },
    ],
  },
  {
    name: 'Fuse Workshop',
    hint: 'Collect +bomb and the blasting plunger. F fires a planted bomb early.',
    rows: [
      '#############',
      '#.+S.*.....b#',
      '#.#..#..#.#.#',
      '#i...*......#',
      '##*###..#.#.#',
      '#....S..*..k#',
      '#.#..#..###.#',
      '#....*......#',
      '#.#..#..#.#.#',
      '#...b*..S..E#',
      '#############',
    ],
    rewards: [
      { x: 5, y: 3, type: 'bomb' },
      { x: 8, y: 5, type: 'shield' },
      { x: 5, y: 7, type: 'fire' },
    ],
  },
  {
    name: 'The Proving Ground',
    hint: 'They dodge blasts now. Use shafts and corners to set a trap.',
    rows: [
      '#############',
      '#..S.*......#',
      '#f#..#..#.#.#',
      '#....*..S.k.#',
      '#.#.###.*.#.#',
      '#...*...*...#',
      '#.*.###.#.#.#',
      '#.b.S...*...#',
      '#.#.*.#.#.#.#',
      '#...*k..S..E#',
      '#############',
    ],
    rewards: [
      { x: 5, y: 3, type: 'bomb' },
      { x: 8, y: 5, type: 'ignitor' },
      { x: 4, y: 8, type: 'shield' },
      { x: 8, y: 7, type: 'fire' },
    ],
  },
];
