#!/usr/bin/env node
// Writes solar-system/ss-core.js — the physics core between the SS-CORE markers of
// solar-system/index.html, wrapped as createSolarCore() — so other pages (Daily
// Orbit's worker) run the SAME physics as the sim without a copy that can drift.
// The sim test fails when this file is stale. Run after any physics edit:
//
//   node tools/sync-core.mjs            write the file
//   node tools/sync-core.mjs --check    exit 1 if the file on disk is stale
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const PAGE = new URL('../solar-system/index.html', import.meta.url);
const OUT = new URL('../solar-system/ss-core.js', import.meta.url);

export function renderCore(){
  const html = readFileSync(PAGE, 'utf8');
  const core = html.split('/*SS-CORE-START*/')[1]?.split('/*SS-CORE-END*/')[0];
  if (!core) throw new Error('SS-CORE markers not found in solar-system/index.html');
  return `// GENERATED by tools/sync-core.mjs from solar-system/index.html — do not edit here.
// The N-body physics core of the Solar System sim (AU, years, solar masses), DOM-free.
// createSolarCore() returns a fresh, independent instance.
function createSolarCore(){
${core}
  return {
    G, DT, KMS, SUN, planets, EARTH, MOON, bodies,
    reset, advance, energy, keplerProp, lambertV, bestTransfer, transferScan, probeCorrection,
    arrangeForDate, elementsAt, julianDay, JD_J2000,
    addProbe: p => { probes.push(p); return p; },
    clearProbes: () => { probes.length = 0; },
    clearSpecks: () => { belt.length = 0; storm.length = 0; },
    state: () => ({ t, comets, belt, storm, probes, E0 }),
    setRate: r => { timeRate = r; },
    onEmit: f => { EMIT = f; },
    onFx: f => { FX = f; }
  };
}
if (typeof module !== 'undefined' && module.exports) module.exports = { createSolarCore };
`;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())){
  const want = renderCore();
  if (process.argv.includes('--check')){
    const have = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    if (have !== want){ console.error('solar-system/ss-core.js is STALE — run: node tools/sync-core.mjs'); process.exit(1); }
    console.log('ss-core.js is in sync');
  } else {
    writeFileSync(OUT, want);
    console.log(`wrote solar-system/ss-core.js (${want.length.toLocaleString()} bytes)`);
  }
}
