// Animal Detective — animal database (~96 common animals).
// Schema documented in questions.js predicates and the project plan.
// Edge cases handled: bat (mammal that flies), penguin (bird that can't fly),
// dolphin/whale (mammal in water), kangaroo (bipedal, legs=2).

window.AD_ANIMALS = [
  // ── MAMMALS ────────────────────────────────────────────────────────────
  {
    slug: "dog", name: "Dog", emoji: "🐕",
    fact: "Dogs can learn over 100 different words!",
    class: "mammal", size: "medium", legs: 4, diet: "omnivore", type: "pet",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "cat", name: "Cat", emoji: "🐈",
    fact: "Cats spend up to 70% of their lives sleeping.",
    class: "mammal", size: "small", legs: 4, diet: "carnivore", type: "pet",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "cow", name: "Cow", emoji: "🐄",
    fact: "Cows have four stomach compartments to digest grass.",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "farm",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: true, isBlackAndWhite: true,
    habitat: ["farm"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "horse", name: "Horse", emoji: "🐎",
    fact: "Horses can sleep both lying down and standing up.",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "farm",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm", "savanna"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "pig", name: "Pig", emoji: "🐖",
    fact: "Pigs are smarter than dogs and can learn tricks!",
    class: "mammal", size: "medium", legs: 4, diet: "omnivore", type: "farm",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "sheep", name: "Sheep", emoji: "🐑",
    fact: "Sheep have great memories and can recognize faces.",
    class: "mammal", size: "medium", legs: 4, diet: "herbivore", type: "farm",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm", "mountain"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "goat", name: "Goat", emoji: "🐐",
    fact: "Some goats can climb trees!",
    class: "mammal", size: "medium", legs: 4, diet: "herbivore", type: "farm",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm", "mountain"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "lion", name: "Lion", emoji: "🦁",
    fact: "A lion's roar can be heard from 5 miles away!",
    class: "mammal", size: "large", legs: 4, diet: "carnivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["savanna"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "tiger", name: "Tiger", emoji: "🐅",
    fact: "Tigers are the only big cats that love swimming!",
    class: "mammal", size: "large", legs: 4, diet: "carnivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: true, hasSpots: false, isBlackAndWhite: false,
    habitat: ["jungle", "forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "elephant", name: "Elephant", emoji: "🐘",
    fact: "Elephants are the only mammals that can't jump.",
    class: "mammal", size: "huge", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["savanna", "jungle"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "giraffe", name: "Giraffe", emoji: "🦒",
    fact: "A giraffe's tongue can be 20 inches long!",
    class: "mammal", size: "huge", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["savanna"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "zebra", name: "Zebra", emoji: "🦓",
    fact: "No two zebras have the same stripe pattern!",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: true, hasSpots: false, isBlackAndWhite: true,
    habitat: ["savanna"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "hippo", name: "Hippo", emoji: "🦛",
    fact: "Hippos can hold their breath underwater for 5 minutes.",
    class: "mammal", size: "huge", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["river", "wetland"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "rhino", name: "Rhino", emoji: "🦏",
    fact: "A rhino's horn is made of the same stuff as your fingernails.",
    class: "mammal", size: "huge", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["savanna"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "kangaroo", name: "Kangaroo", emoji: "🦘",
    fact: "Kangaroos can't walk backwards!",
    class: "mammal", size: "large", legs: 2, diet: "herbivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["savanna", "desert"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "panda", name: "Panda", emoji: "🐼",
    fact: "Pandas eat bamboo for 12 hours every day.",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: true,
    habitat: ["mountain", "forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "polar-bear", name: "Polar Bear", emoji: "🐻‍❄️",
    fact: "Polar bears have black skin under their white fur!",
    class: "mammal", size: "huge", legs: 4, diet: "carnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["arctic"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "brown-bear", name: "Brown Bear", emoji: "🐻",
    fact: "Bears can sleep all winter without eating or drinking.",
    class: "mammal", size: "large", legs: 4, diet: "omnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "mountain"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: true, isNocturnal: false, isLoud: true,
  },
  {
    slug: "wolf", name: "Wolf", emoji: "🐺",
    fact: "Wolves howl to talk to their pack!",
    class: "mammal", size: "large", legs: 4, diet: "carnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "arctic", "mountain"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: true,
  },
  {
    slug: "fox", name: "Fox", emoji: "🦊",
    fact: "Foxes use the Earth's magnetic field to hunt.",
    class: "mammal", size: "medium", legs: 4, diet: "omnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "deer", name: "Deer", emoji: "🦌",
    fact: "Deer antlers grow back every year.",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "rabbit", name: "Rabbit", emoji: "🐇",
    fact: "Rabbits' teeth never stop growing!",
    class: "mammal", size: "small", legs: 4, diet: "herbivore", type: "pet",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home", "forest", "farm"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "mouse", name: "Mouse", emoji: "🐁",
    fact: "Mice can squeeze through holes the size of a pencil.",
    class: "mammal", size: "tiny", legs: 4, diet: "omnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home", "farm", "forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "squirrel", name: "Squirrel", emoji: "🐿️",
    fact: "Squirrels forget where they bury most of their nuts!",
    class: "mammal", size: "small", legs: 4, diet: "omnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "hamster", name: "Hamster", emoji: "🐹",
    fact: "Hamsters can stuff their cheeks with food bigger than their head!",
    class: "mammal", size: "tiny", legs: 4, diet: "omnivore", type: "pet",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "hedgehog", name: "Hedgehog", emoji: "🦔",
    fact: "Hedgehogs roll into a ball when they're scared.",
    class: "mammal", size: "small", legs: 4, diet: "insectivore", type: "pet",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: true, isNocturnal: true, isLoud: false,
  },
  {
    slug: "raccoon", name: "Raccoon", emoji: "🦝",
    fact: "Raccoons wash their food before eating!",
    class: "mammal", size: "medium", legs: 4, diet: "omnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: true, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "home"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "bat", name: "Bat", emoji: "🦇",
    fact: "Bats are the only mammals that can really fly!",
    class: "mammal", size: "tiny", legs: 2, diet: "insectivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: true, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["jungle", "forest", "mountain"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: true,
    laysEggs: false, hibernates: true, isNocturnal: true, isLoud: false,
  },
  {
    slug: "monkey", name: "Monkey", emoji: "🐒",
    fact: "Monkeys talk to each other with hundreds of sounds.",
    class: "mammal", size: "medium", legs: 4, diet: "omnivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["jungle"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "gorilla", name: "Gorilla", emoji: "🦍",
    fact: "Gorillas are mostly vegetarian and very gentle giants.",
    class: "mammal", size: "large", legs: 2, diet: "herbivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["jungle"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "koala", name: "Koala", emoji: "🐨",
    fact: "Koalas sleep up to 22 hours a day!",
    class: "mammal", size: "small", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "jungle"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "sloth", name: "Sloth", emoji: "🦥",
    fact: "Sloths are so slow that algae grows on their fur!",
    class: "mammal", size: "medium", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["jungle"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "otter", name: "Otter", emoji: "🦦",
    fact: "Otters hold hands while sleeping so they don't drift apart!",
    class: "mammal", size: "small", legs: 4, diet: "carnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["river", "ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "skunk", name: "Skunk", emoji: "🦨",
    fact: "Skunks can spray a smell from 10 feet away!",
    class: "mammal", size: "small", legs: 4, diet: "omnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: true, hasSpots: false, isBlackAndWhite: true,
    habitat: ["forest"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "dolphin", name: "Dolphin", emoji: "🐬",
    fact: "Dolphins call each other by name with whistles!",
    class: "mammal", size: "large", legs: 0, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "whale", name: "Whale", emoji: "🐳",
    fact: "The blue whale's heart is the size of a small car.",
    class: "mammal", size: "huge", legs: 0, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "seal", name: "Seal", emoji: "🦭",
    fact: "Seals can sleep underwater holding their breath.",
    class: "mammal", size: "large", legs: 4, diet: "carnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["arctic", "ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "camel", name: "Camel", emoji: "🐪",
    fact: "Camels store fat in their humps, not water!",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["desert"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "beaver", name: "Beaver", emoji: "🦫",
    fact: "Beavers' teeth are orange because of iron!",
    class: "mammal", size: "medium", legs: 4, diet: "herbivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["river", "wetland", "forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "llama", name: "Llama", emoji: "🦙",
    fact: "Llamas spit when they're upset!",
    class: "mammal", size: "medium", legs: 4, diet: "herbivore", type: "farm",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["mountain", "farm"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "bison", name: "Bison", emoji: "🦬",
    fact: "Bison can run 35 mph despite their huge size!",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["savanna"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "cheetah", name: "Cheetah", emoji: "🐆",
    fact: "Cheetahs are the fastest land animals — they can sprint 70 mph!",
    class: "mammal", size: "large", legs: 4, diet: "carnivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["savanna"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "moose", name: "Moose", emoji: "🫎",
    fact: "A moose's antlers can spread over 6 feet across!",
    class: "mammal", size: "huge", legs: 4, diet: "herbivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "arctic"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "donkey", name: "Donkey", emoji: "🫏",
    fact: "Donkeys have great memories and never forget a face!",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "farm",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "orca", name: "Orca", emoji: "🐋",
    fact: "Orcas are the biggest dolphins and hunt in family pods!",
    class: "mammal", size: "huge", legs: 0, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: true,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "bull", name: "Bull", emoji: "🐂",
    fact: "Bulls can weigh over 2,000 pounds!",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "farm",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "water-buffalo", name: "Water Buffalo", emoji: "🐃",
    fact: "Water buffalo love wallowing in mud to cool off and keep bugs away!",
    class: "mammal", size: "huge", legs: 4, diet: "herbivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["wetland", "river"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "ram", name: "Ram", emoji: "🐏",
    fact: "A ram's curly horns can weigh as much as 30 pounds!",
    class: "mammal", size: "medium", legs: 4, diet: "herbivore", type: "farm",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm", "mountain"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "wild-boar", name: "Wild Boar", emoji: "🐗",
    fact: "Wild boars use their tusks to dig up roots and bugs!",
    class: "mammal", size: "medium", legs: 4, diet: "omnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "jungle"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: true,
  },
  {
    slug: "rat", name: "Rat", emoji: "🐀",
    fact: "Rats are super smart and can solve mazes faster than you'd expect!",
    class: "mammal", size: "small", legs: 4, diet: "omnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home", "farm"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "bactrian-camel", name: "Bactrian Camel", emoji: "🐫",
    fact: "Bactrian camels have TWO humps that store fat for long journeys!",
    class: "mammal", size: "large", legs: 4, diet: "herbivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["desert", "mountain"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "badger", name: "Badger", emoji: "🦡",
    fact: "Badgers dig huge underground burrows called setts!",
    class: "mammal", size: "medium", legs: 4, diet: "omnivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: true, hasSpots: false, isBlackAndWhite: true,
    habitat: ["forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "orangutan", name: "Orangutan", emoji: "🦧",
    fact: "Orangutans build a new nest in the trees every night to sleep in!",
    class: "mammal", size: "large", legs: 2, diet: "omnivore", type: "zoo",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["jungle"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "mammoth", name: "Mammoth", emoji: "🦣",
    fact: "Woolly mammoths lived during the Ice Age and had thick shaggy fur to stay warm!",
    class: "mammal", size: "huge", legs: 4, diet: "herbivore", type: "wild",
    hasFur: true, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: true,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["arctic"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: true,
  },

  // ── BIRDS ──────────────────────────────────────────────────────────────
  {
    slug: "chicken", name: "Chicken", emoji: "🐔",
    fact: "Chickens can recognize over 100 different faces!",
    class: "bird", size: "medium", legs: 2, diet: "omnivore", type: "farm",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "duck", name: "Duck", emoji: "🦆",
    fact: "Ducks have waterproof feathers!",
    class: "bird", size: "small", legs: 2, diet: "omnivore", type: "farm",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["river", "wetland", "farm"],
    livesInWater: false, canFly: true, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "owl", name: "Owl", emoji: "🦉",
    fact: "Owls can turn their heads almost all the way around!",
    class: "bird", size: "medium", legs: 2, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["forest"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: true, isLoud: true,
  },
  {
    slug: "eagle", name: "Eagle", emoji: "🦅",
    fact: "Eagles can spot a rabbit from 2 miles away!",
    class: "bird", size: "large", legs: 2, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["mountain", "forest"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "parrot", name: "Parrot", emoji: "🦜",
    fact: "Some parrots can learn over 1,000 words!",
    class: "bird", size: "small", legs: 2, diet: "omnivore", type: "pet",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["jungle", "home"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "penguin", name: "Penguin", emoji: "🐧",
    fact: "Penguins can't fly but they swim like fish!",
    class: "bird", size: "medium", legs: 2, diet: "carnivore", type: "zoo",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: true,
    habitat: ["arctic", "ocean"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "flamingo", name: "Flamingo", emoji: "🦩",
    fact: "Flamingos are pink because they eat pink shrimp!",
    class: "bird", size: "medium", legs: 2, diet: "omnivore", type: "zoo",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["wetland"],
    livesInWater: false, canFly: true, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "peacock", name: "Peacock", emoji: "🦚",
    fact: "Only male peacocks have those huge fancy tails!",
    class: "bird", size: "medium", legs: 2, diet: "omnivore", type: "zoo",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["jungle", "forest"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "swan", name: "Swan", emoji: "🦢",
    fact: "Swans mate for life and stay together forever!",
    class: "bird", size: "large", legs: 2, diet: "herbivore", type: "wild",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["river", "wetland"],
    livesInWater: false, canFly: true, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "turkey", name: "Turkey", emoji: "🦃",
    fact: "Wild turkeys can fly up to 55 mph!",
    class: "bird", size: "large", legs: 2, diet: "omnivore", type: "farm",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm", "forest"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "rooster", name: "Rooster", emoji: "🐓",
    fact: "Roosters crow at dawn to mark their territory!",
    class: "bird", size: "medium", legs: 2, diet: "omnivore", type: "farm",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "crow", name: "Crow", emoji: "🐦‍⬛",
    fact: "Crows are so smart they can use tools and remember faces!",
    class: "bird", size: "small", legs: 2, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "home"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "hummingbird", name: "Hummingbird", emoji: "🐦",
    fact: "Hummingbirds can flap their wings up to 80 times per second!",
    class: "bird", size: "tiny", legs: 2, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["jungle", "forest"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "goose", name: "Goose", emoji: "🪿",
    fact: "Geese fly in a V shape to help each other go farther!",
    class: "bird", size: "medium", legs: 2, diet: "herbivore", type: "wild",
    hasFur: false, hasFeathers: true, hasScales: false, hasShell: false,
    hasWings: true, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["wetland", "river", "farm"],
    livesInWater: false, canFly: true, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },

  // ── SEA CREATURES ─────────────────────────────────────────────────────
  {
    slug: "fish", name: "Fish", emoji: "🐟",
    fact: "Fish breathe by pulling oxygen out of water through their gills.",
    class: "fish", size: "small", legs: 0, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: true, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean", "river"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "clownfish", name: "Clownfish", emoji: "🐠",
    fact: "Clownfish live safely inside stinging sea anemones!",
    class: "fish", size: "tiny", legs: 0, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: true, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: true, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "pufferfish", name: "Pufferfish", emoji: "🐡",
    fact: "Pufferfish blow up like a balloon when they're scared!",
    class: "fish", size: "small", legs: 0, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: true, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "shark", name: "Shark", emoji: "🦈",
    fact: "Sharks have rows and rows of teeth — they grow new ones forever!",
    class: "fish", size: "large", legs: 0, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "octopus", name: "Octopus", emoji: "🐙",
    fact: "Octopuses have 3 hearts and blue blood!",
    class: "invertebrate", size: "medium", legs: 8, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "squid", name: "Squid", emoji: "🦑",
    fact: "Squids can squirt ink to confuse predators!",
    class: "invertebrate", size: "medium", legs: 8, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "jellyfish", name: "Jellyfish", emoji: "🪼",
    fact: "Jellyfish have been around for over 500 million years!",
    class: "invertebrate", size: "small", legs: 0, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "crab", name: "Crab", emoji: "🦀",
    fact: "Crabs walk sideways because of their leg joints!",
    class: "invertebrate", size: "small", legs: 8, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: true,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "lobster", name: "Lobster", emoji: "🦞",
    fact: "Lobsters can live to be over 100 years old!",
    class: "invertebrate", size: "small", legs: 8, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: true,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "shrimp", name: "Shrimp", emoji: "🦐",
    fact: "Some shrimp snap their claws so hard it makes lightning!",
    class: "invertebrate", size: "tiny", legs: 8, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: true,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["ocean"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },

  // ── REPTILES & AMPHIBIANS ─────────────────────────────────────────────
  {
    slug: "snake", name: "Snake", emoji: "🐍",
    fact: "Some snakes can swallow animals bigger than their head!",
    class: "reptile", size: "medium", legs: 0, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: true, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["jungle", "desert", "forest"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "turtle", name: "Turtle", emoji: "🐢",
    fact: "Some sea turtles can live for over 100 years!",
    class: "reptile", size: "small", legs: 4, diet: "omnivore", type: "pet",
    hasFur: false, hasFeathers: false, hasScales: true, hasShell: true,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["river", "ocean", "wetland"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "frog", name: "Frog", emoji: "🐸",
    fact: "Frogs drink water through their skin!",
    class: "amphibian", size: "tiny", legs: 4, diet: "insectivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["wetland", "river", "jungle"],
    livesInWater: false, canFly: false, canSwim: true, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: true, isLoud: true,
  },
  {
    slug: "lizard", name: "Lizard", emoji: "🦎",
    fact: "Lizards can drop their tails when scared and grow new ones!",
    class: "reptile", size: "small", legs: 4, diet: "insectivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: true, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["desert", "jungle", "forest"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "crocodile", name: "Crocodile", emoji: "🐊",
    fact: "Crocodiles haven't changed much in 200 million years!",
    class: "reptile", size: "large", legs: 4, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: true, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["river", "wetland"],
    livesInWater: true, canFly: false, canSwim: true, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },

  // ── INSECTS, ARACHNIDS & OTHER INVERTEBRATES ──────────────────────────
  {
    slug: "bee", name: "Bee", emoji: "🐝",
    fact: "Bees do a special dance to tell each other where flowers are!",
    class: "invertebrate", size: "tiny", legs: 6, diet: "herbivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: true, hasTail: false, hasHorns: false,
    hasStripes: true, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "farm", "wetland"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "butterfly", name: "Butterfly", emoji: "🦋",
    fact: "Butterflies taste with their feet!",
    class: "invertebrate", size: "tiny", legs: 6, diet: "herbivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: true, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["forest", "jungle", "farm"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "spider", name: "Spider", emoji: "🕷️",
    fact: "Spiders' silk is stronger than steel — pound for pound!",
    class: "invertebrate", size: "tiny", legs: 8, diet: "insectivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home", "forest", "jungle"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "ant", name: "Ant", emoji: "🐜",
    fact: "An ant can lift 50 times its own body weight!",
    class: "invertebrate", size: "tiny", legs: 6, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home", "forest", "farm"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "ladybug", name: "Ladybug", emoji: "🐞",
    fact: "Ladybugs eat hundreds of plant pests every day!",
    class: "invertebrate", size: "tiny", legs: 6, diet: "insectivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: true, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: true, isBlackAndWhite: false,
    habitat: ["forest", "farm"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "grasshopper", name: "Grasshopper", emoji: "🦗",
    fact: "Grasshoppers can jump 20 times the length of their body!",
    class: "invertebrate", size: "tiny", legs: 6, diet: "herbivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: true, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm", "forest"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
  {
    slug: "mosquito", name: "Mosquito", emoji: "🦟",
    fact: "Only female mosquitoes bite — they need blood to make eggs.",
    class: "invertebrate", size: "tiny", legs: 6, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: true, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["wetland", "forest", "home"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "snail", name: "Snail", emoji: "🐌",
    fact: "Snails carry their homes on their backs!",
    class: "invertebrate", size: "tiny", legs: 0, diet: "herbivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: true,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home", "forest", "farm"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "worm", name: "Worm", emoji: "🪱",
    fact: "Worms help plants grow by mixing up the soil!",
    class: "invertebrate", size: "tiny", legs: 0, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["farm", "forest"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "scorpion", name: "Scorpion", emoji: "🦂",
    fact: "Scorpions glow in the dark under blacklight!",
    class: "invertebrate", size: "small", legs: 8, diet: "carnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: true, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["desert"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: false,
    laysEggs: false, hibernates: false, isNocturnal: true, isLoud: false,
  },
  {
    slug: "caterpillar", name: "Caterpillar", emoji: "🐛",
    fact: "Caterpillars eat constantly so they can turn into butterflies or moths!",
    class: "invertebrate", size: "tiny", legs: 6, diet: "herbivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: false, hasTail: false, hasHorns: false,
    hasStripes: true, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "farm"],
    livesInWater: false, canFly: false, canSwim: false, canClimbTrees: true,
    laysEggs: false, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "beetle", name: "Beetle", emoji: "🪲",
    fact: "Beetles make up nearly a quarter of all animal species on Earth!",
    class: "invertebrate", size: "tiny", legs: 6, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: true, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["forest", "farm", "home"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: false,
  },
  {
    slug: "fly", name: "Fly", emoji: "🪰",
    fact: "Houseflies taste with their feet — they walk on food to check it!",
    class: "invertebrate", size: "tiny", legs: 6, diet: "omnivore", type: "wild",
    hasFur: false, hasFeathers: false, hasScales: false, hasShell: false,
    hasWings: true, hasTail: false, hasHorns: false,
    hasStripes: false, hasSpots: false, isBlackAndWhite: false,
    habitat: ["home", "farm"],
    livesInWater: false, canFly: true, canSwim: false, canClimbTrees: true,
    laysEggs: true, hibernates: false, isNocturnal: false, isLoud: true,
  },
];
